version: '3.1'

services:

  db:
    image: postgres:15
    container_name: WX_Open_Finances_DB
    restart: always
    volumes:
      - "../data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: opfina
      POSTGRES_PASSWORD: opfina$123@_
      POSTGRES_DB: openfina

  pgadmin:
    image: dpage/pgadmin4
    container_name: WX_Open_Finances_pgAdmin4
    ports:
      - "10092:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: tech@webtinix.com
      PGADMIN_DEFAULT_PASSWORD: opfina$123@_

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: WX_Open_Finances_Backend
    restart: always
    ports:
      - "10091:8000"
    depends_on:
      - db
    volumes:
      - "../data/backend:/var/www/html"