version: '3.1'

services:

  db:
    image: postgres:15
    build:
      tags:
          - wx-openfina-postgres:1.0
    container_name: WX_Open_Finances_DB
    restart: always
    volumes:
      - "../data/db:/var/lib/postgresql/data"
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./docker-entrypoint-initdb.d/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      # POSTGRES_USER: opfina
      # POSTGRES_PASSWORD: opfina$123@_
      # POSTGRES_DB: openfina
      POSTGRES_USER: root
      POSTGRES_PASSWORD: p@$$w0rd
      POSTGRES_DB: opdb
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    networks:
        - wx_openfina_db

  pgadmin:
    image: dpage/pgadmin4:8.0
    build:
      tags:
          - wx-openfina-pgadmin:1.0
    container_name: WX_Open_Finances_pgAdmin4
    ports:
      - "10092:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: tech@webtinix.com
      PGADMIN_DEFAULT_PASSWORD: p@$$w0rd
    networks:
        - wx_openfina_db

  web:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
          - wx-openfina-web:1.0
    image: wx-openfina-web:1.0
    container_name: WX_Open_Finances_Backend
    restart: always
    command: ["python", "src/manage.py", "migrate"]
    ports:
      - "10091:8000"
    depends_on:
      - db
    networks:
        - wx_openfina_web
        - wx_openfina_db

networks:
    wx_openfina_web:
        driver: bridge
    wx_openfina_db:
        driver: bridge